---
- name: install base packages
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: install the packages...
      apt:
        pkg: "{{ item }}"
        state: latest
      with_items:
        - xinetd
        - git

- name: install toddles repositories 
  hosts: all
  gather_facts: true
  tasks:
    - name: Checkout from git
#      become_user: toddm
#      become_method: sudo
      git: repo=git@github.com:toddles/ops_things.git dest=~/src/ops_things accept_hostkey=true

- name: install ops dependencies and agents
  hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root
  roles:
#    - ssh
#    - operations
    - debian_family_base


